version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    groups:
      production-minor-patch:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      development-minor-patch:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
