allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - sharp
  - workerd

overrides:
  'static-eval@<=2.0.1': '>=2.0.2'
  'static-eval@<2.0.0': '>=2.0.0'
  'minimist@<0.2.1': '>=0.2.1'
  'minimist@<0.2.4': '>=0.2.4'
  'cookie@<0.7.0': '>=0.7.0 <2.0.0'
  typescript: '>=6.0.2 <7.0.0'
